name: fill_3d_7d_forward_change

on:
  schedule:
    - cron: '10,40 13-20 * * 1-5'  # 每小时的第10分和40分，周一至周五
    - cron: '10 1,7,13,19 * * 0,6' # 周六,日，运行4次

  workflow_dispatch:   # ✅ 允许手动触发

jobs:
  fill_3d_7d_forward_change:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install rclone
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone

      - name: Create rclone config file
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF_BASE64 }}" | base64 --decode > ~/.config/rclone/rclone.conf

      - name: Install yfinance
        run: |
          pip install yfinance

      - name: Create credential file
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > credentials.json

      - name: Run fill_3d_7d_forward_change.py
        run: |
          python fill_3d_7d_forward_change.py