name: Option Scanner (Google Sheets)

on:
  schedule:
    - cron: '0 0-23 * * 1-4'   # 周一～周四（蒙特利尔时间 00:00–23:00 每小时一次）
    - cron: '0 0-20 * * 5'     # 周五（蒙特利尔时间 00:00–20:00 每小时一次）
    - cron: '0 22-23 * * 0'    # 周日（蒙特利尔时间 18:00–19:00）
    - cron: '0 0-3 * * 1'      # 周日（蒙特利尔时间 20:00–23:00，UTC已是周一）

  workflow_dispatch:   # ✅ 允许手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create credential file
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > credentials.json

      - name: Install rclone
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone

      - name: Create rclone config file
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF_BASE64 }}" | base64 --decode > ~/.config/rclone/rclone.conf

      - name: Run script
        run: |
          python daily_top_options.py


