name: Option Scanner (Google Sheets)

on:
  schedule:
    - cron: '0 16-23 * * 0'   # 周日 16点到23点
    - cron: '0 * * * 1-5'     # 周一到周五每小时一次
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create credential file
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > credentials.json

      - name: Run script
        run: |
          python daily_top_options.py

      - name: Install rclone
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone

      - name: Upload files to Google Drive
        run: |
          echo "${{ secrets.RCLONE_CONF }}" > rclone.conf
          rclone --config=rclone.conf copy option_activity_log.xlsx gdrive:/your_folder/
          rclone --config=rclone.conf copy score_*.png gdrive:/your_folder/
