name: Option Scanner (Google Sheets)

on:
  schedule:
    - cron: '0 * * * 1-5'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create credential file
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > credentials.json

      - name: Run script
        run: |
          python daily_top_options.py
