name: Update ETF Price
on:
  schedule:
    - cron: '*/15 * * * 0-5'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip list

      - name: Create credential file
        run: echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > credentials.json

      - name: Run update_etf_prices.py
        run: python update_etf_prices.py
