name: Update ETF Price
on:
  schedule:
    - cron: '*/15 * * * 0-5'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Debug python environment
        run: |
          python --version
          which python
          python -m pip --version
          python -m pip list

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip list

      - name: Create credential file
        run: echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > credentials.json

      - name: Run update_etf_prices.py
        run: python update_etf_prices.py
