name: update_etf_prices

on:
  schedule:
    - cron: '30 * * * 0-5' # 周日到周五，每小时一次

  workflow_dispatch:   # ✅ 允许手动触发

jobs:
  update_etf_prices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install yfinance pandas google-auth google-auth-httplib2 google-api-python-client

      - name: Create credentials file from base64 secret
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_JSON_BASE64 }}" | base64 -d > credentials.json

      - name: Run python update_etf_prices.py
        run: |
          python update_etf_prices.py
